version: '3.8'

services:
  app:
    image: "school-website"
    container_name: "school-website"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - OUTPUT=standalone
    env_file:
      - .env.docker
    # volumes:
    #   - .:/app
    #   - /app/node_modules
