version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs-docker
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
