import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="min-w-full w-fit h-fit">
      <body className={inter.className}>
        <div className="grow w-full min-h-[calc(100vh-100px)] relative flex justify-center">
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
