# version: "3.8"

services:
  frontend:
    image: "school-website"
    container_name: "dev-elektronik-frontend"
    build: frontend
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      # nadpisujemy .env fronta
      - STRAPI_INTERNAL_URL=http://strapi:5000
    env_file:
      - frontend/.env
    networks:
      - dev-elektronik-network
      - timetable-api
    volumes:
      - ./frontend/.env:/app/.env
    depends_on:
      strapi:
        condition: service_healthy

  strapi:
    container_name: dev-elektronik-strapi
    platform: linux/amd64
    build: 
      context: "./strapi/."
      platforms:
        - "linux/amd64"
    image: strapi:latest
    restart: unless-stopped
    env_file: ./strapi/.env
    volumes:
      - ./strapi/config:/opt/app/config
      - ./strapi/src:/opt/app/src
      - ./strapi/package.json:/opt/package.json
      - ./strapi/package-lock.json:/opt/package-lock.json
      - ./strapi/.env:/opt/app/.env
      - ./strapi/public:/opt/app/public
      - ./strapi/types:/opt/app/types
      - ./strapi/backups:/opt/app/backups
      - ./strapi/data:/opt/app/data
    ports:
      - '5000:5000'
      - '5173:5173'
    networks:
      - dev-elektronik-network
    healthcheck:
      test:
        - CMD-SHELL
        - wget --quiet --spider http://127.0.0.1:5000/_health || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

networks:
  dev-elektronik-network:
    name: dev-elektronik-network
    driver: bridge
  timetable-api:
    external: true
