version: '3'
services:
  strapi:
    container_name: strapi
    platform: linux/arm64/v8
    build: .
    image: strapi:latest
    restart: unless-stopped
    env_file: .env
    environment:
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      APP_KEYS: ${APP_KEYS}
      NODE_ENV: ${NODE_ENV}
    volumes:
      - ./config:/opt/app/config
      - ./src:/opt/app/src
      - ./package.json:/opt/package.json
      - ./package-lock.json:/opt/package-lock.json
      - ./.env:/opt/app/.env
      - ./public/uploads:/opt/app/public/uploads
      # - ./database/data.db:/opt/app/database/data.db
    ports:
      - '5000:5000'
    networks:
      - strapi
    depends_on:
      - db
  db:
    image: mariadb:latest
    platform: linux/arm64/v8
    container_name: db
    restart: always
    # env_file: .env
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      # So you don't have to use root, but you can if you like
      MYSQL_USER: ${DATABASE_USERNAME}
      # You can use whatever password you like
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      # Password for root access
      # MYSQL_ROOT_PASSWORD:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
    networks:
      - strapi

volumes:
  strapi-data:
  my-db:

networks:
  strapi:
    name: Strapi
    driver: bridge
